#include "Assets.h"
#include "rlgl.h"
#include <cassert>

Assets assets;

static void LoadAudio();
static void LoadMeshes();
static void LoadTextures();
static void LoadMaterials();

static void UnloadMaterials();
static void UnloadTextures();
static void UnloadMeshes();
static void UnloadAudio();

void LoadAssets()
{
    LoadAudio();
    LoadMeshes();
    LoadTextures();
    LoadMaterials();
}

void UnloadAssets()
{
    UnloadMaterials();
    UnloadTextures();
    UnloadMeshes();
    UnloadAudio();
}

void LoadAudio()
{
    Audios& audio = assets.audio;
    audio.fire_rifle = LoadSound("./assets/audio/fire_rifle.wav");
    audio.fire_shotgun = LoadSound("./assets/audio/fire_shotgun.wav");
    audio.fire_grenade = LoadSound("./assets/audio/fire_grenade.wav");
    audio.fire_missile = LoadSound("./assets/audio/fire_missile.wav");
    audio.fire_dasher = LoadSound("./assets/audio/fire_dasher.wav");

    audio.hit = LoadSound("./assets/audio/hit.wav");
    audio.hit_mech = LoadSound("./assets/audio/hit_mech.wav");

    audio.heat_overheat = LoadSound("./assets/audio/heat_overheat.wav");
    audio.heat_restore = LoadSound("./assets/audio/heat_restore.wav");
}

void UnloadAudio()
{
    Audios& audio = assets.audio;
    UnloadSound(audio.heat_restore);
    UnloadSound(audio.heat_overheat);

    UnloadSound(audio.hit_mech);
    UnloadSound(audio.hit);

    UnloadSound(audio.fire_dasher);
    UnloadSound(audio.fire_missile);
    UnloadSound(audio.fire_grenade);
    UnloadSound(audio.fire_shotgun);
    UnloadSound(audio.fire_rifle);
}

void LoadMeshes()
{
    auto LoadMesh = [](Mesh* mesh, const char* file)
    {
        Model model = LoadModel(file);
        assert(model.meshCount == 1);
        mesh = &model.meshes[0];
        model.meshCount = 0;
        UnloadModel(model);
    };

    Meshes& mesh = assets.mesh;

    // Mech
	LoadMesh(&mesh.torso, "./assets/meshes/mech_torso.obj");
	LoadMesh(&mesh.legs, "./assets/meshes/mech_legs.obj");

    // Buildings
	LoadMesh(&mesh.td, "./assets/meshes/bld_td.obj");
	LoadMesh(&mesh.bmo, "./assets/meshes/bld_bmo.obj");
	LoadMesh(&mesh.condo, "./assets/meshes/bld_condo.obj");

    // Projectiles
	LoadMesh(&mesh.bullet, "./assets/meshes/prj_straight.obj");
	LoadMesh(&mesh.grenade, "./assets/meshes/prj_grenade.obj");
	LoadMesh(&mesh.missile, "./assets/meshes/prj_missile.obj");

    // Gear
    //Model gear_rifle;
    //Model gear_shotgun;
    //Model gear_grenade;
}

void UnloadMeshes()
{
    Meshes& mesh = assets.mesh;
    UnloadMesh(mesh.torso);
    UnloadMesh(mesh.legs);

    UnloadMesh(mesh.td);
    UnloadMesh(mesh.bmo);
    UnloadMesh(mesh.condo);

    UnloadMesh(mesh.bullet);
    UnloadMesh(mesh.grenade);
    UnloadMesh(mesh.missile);
}

void LoadMaterials()
{
    // "texture0", "texture1", and "texture2" are queried by default on-shader load.
    // ie if I want to sample a texture for shadow-mapping, add a uniform called texture1 and shader.locs[SHADER_LOC_MAP_SPECULAR].texture
    //shader.locs[SHADER_LOC_MAP_DIFFUSE] = rlGetLocationUniform(shader.id, RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE0);  // SHADER_LOC_MAP_ALBEDO / DIFFUSE
    //shader.locs[SHADER_LOC_MAP_SPECULAR] = rlGetLocationUniform(shader.id, RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE1); // SHADER_LOC_MAP_METALNESS / SPECULAR
    //shader.locs[SHADER_LOC_MAP_NORMAL] = rlGetLocationUniform(shader.id, RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE2);   // SHADER_LOC_MAP_NORMAL

    Shader skinning = LoadShader("./assets/shaders/skinning.vs", "./assets/shaders/skinning.fs");
    Shader lighting = LoadShader("./assets/shaders/base.vs", "./assets/shaders/lighting.fs");
    Shader depth = LoadShader("./assets/shaders/base.vs", "./assets/shaders/depth.fs");

    Materials& material = assets.material;
    material.flat = LoadMaterialDefault();
    
    material.skinning = LoadMaterialDefault();
    material.skinning.shader = skinning;

    material.lighting = LoadMaterialDefault();
    material.lighting.shader = lighting;
    material.lighting.shader.locs[SHADER_LOC_VECTOR_VIEW] = GetShaderLocation(material.lighting.shader, "viewPos");
}

void UnloadMaterials()
{
    // TODO -- Test this (I'm confused about UnloadMaterial passing by-value, and if its valid to double-delete an OpenGL shader)...
    //auto UnloadMaterialSafe = [](Material material)
    //{
    //    if (IsMaterialValid(material))
    //        UnloadMaterial(material);
    //};

    Materials& material = assets.material;
    UnloadMaterial(material.lighting);
    UnloadMaterial(material.depth);
    UnloadMaterial(material.flat);
}

void LoadTextures()
{
    // White 1x1 texture
    {
        Image image = GenImageColor(1, 1, WHITE);
        assets.texture.white = LoadTextureFromImage(image);
        UnloadImage(image);

        // Alternatives:
        //  -LoadImageRaw() to read from char* of pixels
        //  -rlLoadTexture() to manually specify texture information
        //  -rlGetTextureIdDefault() contains a handle to a 1x1 white texture generated by raylib during startup
    }

    // Gradient test
    {
        Color src = RED;
        Color dst = ORANGE;
        src.a = dst.a = 128;

        Image image = GenImageGradientLinear(64, 64, 0, src, dst);
        assets.texture.gradient = LoadTextureFromImage(image);
        UnloadImage(image);
    }
}

void UnloadTextures()
{
    Textures& texture = assets.texture;
    UnloadTexture(texture.white);
    UnloadTexture(texture.gradient);
}
